apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: trilium-external
  namespace: trilium
  labels:
    app: trilium
spec:
  parentRefs:
  - name: gateway-external
    namespace: gateway
  hostnames:
  - "trilium.homelabjunkie.com" 
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: trilium-server
      port: 8080
      kind: Service