apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  labels:
    app: trilium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn