# app|namespace|pvc|workload-kind|workload-name|service|ingress
trilium|trilium|trilium-data|deployment|trilium|trilium|trilium
vaultwarden|vaultwarden|vaultwarden-data|deployment|vaultwarden|vaultwarden|vaultwarden
portainer|portainer|portainer|deployment|portainer|portainer|portainer
grafana|monitoring|monitoring-grafana|deployment|monitoring-grafana|monitoring-grafana|grafana
loki|logging|storage-loki-0|statefulset|loki|loki-gateway|
prometheus|monitoring|prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0|statefulset|prometheus-monitoring-kube-prometheus-prometheus|||
alertmanager|monitoring|alertmanager-monitoring-kube-prometheus-alertmanager-db-alertmanager-monitoring-kube-prometheus-alertmanager-0|statefulset|alertmanager-monitoring-kube-prometheus-alertmanager|||
