apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    type: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://charts.goauthentik.io/
    chart: authentik
    targetRevision: 2.0.0
    helm:
      releaseName: authentik
      values: |
        # Secret Key
        secretKey: |
          {{ index .Secret "authentik-secret-key" "secretKey" | b64dec }}
        
        # PostgreSQL
        postgresql:
          enabled: true
          auth:
            username: authentik
            password: |
              {{ index .Secret "authentik-postgres-password" "postgresPassword" | b64dec }}
            database: authentik
        
        # Redis
        redis:
          enabled: true
          auth:
            password: |
              {{ index .Secret "authentik-redis-password" "redisPassword" | b64dec }}
        
        # Server
        server:
          replicas: 1
        
        # Worker
        worker:
          replicas: 1
        
        # Disable default ingress (we'll use Gateway API)
        ingress:
          enabled: false
        
        # Service
        service:
          type: ClusterIP
          ports:
            http: 9000
            https: 9443
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  parentRefs:
  - name: gateway-external  # Change to your gateway name
    namespace: gateway  # Change to your gateway namespace
  hostnames:
  - "auth.homelabjunkie.com"  # Change to your domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: authentik-server
      port: 9000
      kind: Service