apiVersion: v1
kind: Secret
metadata:
  name: searxng
  namespace: searxng
type: Opaque
stringData:
  SEARXNG_SECRET: "e690a8a5d954d89cb748a814ba83de3ebd02c70ccc721722bf23bbd27a6c1f3c"  # Generate with: openssl rand -hex 32