apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://longhorn@us-east-1/"
  credentialSecret: "longhorn-minio-credentials"  # Optional, if credentials are required

