apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage-test-pvc
  namespace: nginx-test 
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
